SUPABASE_URL      = "https://avsihyccuawehjmesqfq.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2c2loeWNjdWF3ZWhqbWVzcWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDc5NTksImV4cCI6MjA2OTI4Mzk1OX0.VUbXPYnM9WVIGoAOSCEHrBD_GQfyjmwVP2JmcmvxKkg"
